OTEL_SDK_DISABLED: True
CREWAI_TELEMETRY_ENABLED: False

USE_OLLAMA: False
MODEL_URL: http://localhost:11434
TEMPERATURE: 0.2

#MODEL: mistral:7b
MODEL: gpt-4

LLM_TIMEOUT: 600
CORE_AGENT_TIMEOUT: 600
REFERENCE_AGENT_TIMEOUT: 1800
BIBTEX_AGENT_TIMEOUT: 600
VALIDATOR_AGENT_TIMEOUT: 600
GOVERNANCE_AGENT_TIMEOUT: 600

MAX_AGENT_ITERATIONS: 10
MAX_RPM: 20
ENABLE_MEMORY: False
VERBOSE: True

SEMANTIC_SCHOLAR_USER_AGENT: AcademicMultiAgent/1.0

# === Logging ===
LOG_LEVEL: INFO